version: "3"

services:
  app:
    image: ghcr.io/zuoa/viewnow:main
    container_name: viewnow
    restart: "always"
    ports:
      - "7080:7080"
    volumes:
      - ./data/app:/app
    environment:
      - "TZ=Asia/Shanghai"
      - "SECRET_KEY=123123"
  redis:
    image: redis:7
    container_name: redis
    restart: always
    environment:
      - "TZ=Asia/Shanghai"
    volumes:
      - ./data/redis:/data
      - ./data/logs/redis:/logs
    networks:
      - bridge_net
# 网络配置
networks:
  bridge_net:
    driver: bridge